spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  ai:
    name: tresende-mcp
    version: 0.0.1
  main:
    banner-mode: off
    web-application-type: none

#no-log
logging:
  pattern:
    console: