spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  ai:
    name: tresende-mcp
    version: 0.0.1
    server:
      name: tresende-mcp-server
      version: 1.0.0
      type: SYNC
      sse-message-endpoint: /mcp/messages