spring:
  application:
    name: demo
  ai:
    name: tresende-mcp
    version: 0.0.1
    server:
      name: tresende-mcp-server
      version: 1.0.0
      type: SYNC
      sse-message-endpoint: /mcp/messages